// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/proto/approval.proto

package approvalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApprovalService_SubscribeJobUpdates_FullMethodName = "/approval.v1.ApprovalService/SubscribeJobUpdates"
)

// ApprovalServiceClient is the client API for ApprovalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApprovalService provides gRPC streaming for job status updates.
// The api-gateway subscribes to receive real-time notifications that it
// forwards to WebSocket clients.
type ApprovalServiceClient interface {
	// SubscribeJobUpdates opens a server-side stream that pushes job status
	// updates to the connected api-gateway instance. The stream remains open
	// and sends notifications as jobs progress through the pipeline.
	SubscribeJobUpdates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobUpdateNotification], error)
}

type approvalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApprovalServiceClient(cc grpc.ClientConnInterface) ApprovalServiceClient {
	return &approvalServiceClient{cc}
}

func (c *approvalServiceClient) SubscribeJobUpdates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobUpdateNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApprovalService_ServiceDesc.Streams[0], ApprovalService_SubscribeJobUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, JobUpdateNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApprovalService_SubscribeJobUpdatesClient = grpc.ServerStreamingClient[JobUpdateNotification]

// ApprovalServiceServer is the server API for ApprovalService service.
// All implementations must embed UnimplementedApprovalServiceServer
// for forward compatibility.
//
// ApprovalService provides gRPC streaming for job status updates.
// The api-gateway subscribes to receive real-time notifications that it
// forwards to WebSocket clients.
type ApprovalServiceServer interface {
	// SubscribeJobUpdates opens a server-side stream that pushes job status
	// updates to the connected api-gateway instance. The stream remains open
	// and sends notifications as jobs progress through the pipeline.
	SubscribeJobUpdates(*SubscribeRequest, grpc.ServerStreamingServer[JobUpdateNotification]) error
	mustEmbedUnimplementedApprovalServiceServer()
}

// UnimplementedApprovalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApprovalServiceServer struct{}

func (UnimplementedApprovalServiceServer) SubscribeJobUpdates(*SubscribeRequest, grpc.ServerStreamingServer[JobUpdateNotification]) error {
	return status.Error(codes.Unimplemented, "method SubscribeJobUpdates not implemented")
}
func (UnimplementedApprovalServiceServer) mustEmbedUnimplementedApprovalServiceServer() {}
func (UnimplementedApprovalServiceServer) testEmbeddedByValue()                         {}

// UnsafeApprovalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApprovalServiceServer will
// result in compilation errors.
type UnsafeApprovalServiceServer interface {
	mustEmbedUnimplementedApprovalServiceServer()
}

func RegisterApprovalServiceServer(s grpc.ServiceRegistrar, srv ApprovalServiceServer) {
	// If the following call panics, it indicates UnimplementedApprovalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApprovalService_ServiceDesc, srv)
}

func _ApprovalService_SubscribeJobUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApprovalServiceServer).SubscribeJobUpdates(m, &grpc.GenericServerStream[SubscribeRequest, JobUpdateNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApprovalService_SubscribeJobUpdatesServer = grpc.ServerStreamingServer[JobUpdateNotification]

// ApprovalService_ServiceDesc is the grpc.ServiceDesc for ApprovalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApprovalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "approval.v1.ApprovalService",
	HandlerType: (*ApprovalServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeJobUpdates",
			Handler:       _ApprovalService_SubscribeJobUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/approval.proto",
}
