// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/approval.proto

package approvalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest initiates a subscription stream.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id uniquely identifies the api-gateway instance requesting the stream.
	// Used for logging and connection tracking.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_approval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_approval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_approval_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// JobUpdateNotification carries real-time job status information pushed
// from approval-service to api-gateway, which then forwards it to WebSocket clients.
type JobUpdateNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id identifies the job being updated
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// user_id identifies the job owner (for authorization checks)
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// status reflects the current job state (e.g., "refining", "awaiting_approval", "distributing")
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// message provides human-readable status information
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// preview_url contains the signed S3 URL for the generated image (when type=preview_ready)
	PreviewUrl string `protobuf:"bytes,5,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	// notification_type indicates the nature of this update:
	// - "job_update": General status change
	// - "preview_ready": Image generation complete, preview available
	// - "error": Job encountered an error
	NotificationType string `protobuf:"bytes,6,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	// error contains error details when notification_type="error"
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobUpdateNotification) Reset() {
	*x = JobUpdateNotification{}
	mi := &file_api_proto_approval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdateNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdateNotification) ProtoMessage() {}

func (x *JobUpdateNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_approval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdateNotification.ProtoReflect.Descriptor instead.
func (*JobUpdateNotification) Descriptor() ([]byte, []int) {
	return file_api_proto_approval_proto_rawDescGZIP(), []int{1}
}

func (x *JobUpdateNotification) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobUpdateNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JobUpdateNotification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobUpdateNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobUpdateNotification) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *JobUpdateNotification) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *JobUpdateNotification) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// NotifyJobUpdateResponse acknowledges a NotifyJobUpdate call.
type NotifyJobUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyJobUpdateResponse) Reset() {
	*x = NotifyJobUpdateResponse{}
	mi := &file_api_proto_approval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyJobUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyJobUpdateResponse) ProtoMessage() {}

func (x *NotifyJobUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_approval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyJobUpdateResponse.ProtoReflect.Descriptor instead.
func (*NotifyJobUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_approval_proto_rawDescGZIP(), []int{2}
}

var File_api_proto_approval_proto protoreflect.FileDescriptor

const file_api_proto_approval_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/approval.proto\x12\vapproval.v1\"+\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xdd\x01\n" +
	"\x15JobUpdateNotification\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\vpreview_url\x18\x05 \x01(\tR\n" +
	"previewUrl\x12+\n" +
	"\x11notification_type\x18\x06 \x01(\tR\x10notificationType\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\x19\n" +
	"\x17NotifyJobUpdateResponse2\xca\x01\n" +
	"\x0fApprovalService\x12Z\n" +
	"\x13SubscribeJobUpdates\x12\x1d.approval.v1.SubscribeRequest\x1a\".approval.v1.JobUpdateNotification0\x01\x12[\n" +
	"\x0fNotifyJobUpdate\x12\".approval.v1.JobUpdateNotification\x1a$.approval.v1.NotifyJobUpdateResponseB\x18Z\x16myAgent/api/approvalpbb\x06proto3"

var (
	file_api_proto_approval_proto_rawDescOnce sync.Once
	file_api_proto_approval_proto_rawDescData []byte
)

func file_api_proto_approval_proto_rawDescGZIP() []byte {
	file_api_proto_approval_proto_rawDescOnce.Do(func() {
		file_api_proto_approval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_approval_proto_rawDesc), len(file_api_proto_approval_proto_rawDesc)))
	})
	return file_api_proto_approval_proto_rawDescData
}

var file_api_proto_approval_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_approval_proto_goTypes = []any{
	(*SubscribeRequest)(nil),        // 0: approval.v1.SubscribeRequest
	(*JobUpdateNotification)(nil),   // 1: approval.v1.JobUpdateNotification
	(*NotifyJobUpdateResponse)(nil), // 2: approval.v1.NotifyJobUpdateResponse
}
var file_api_proto_approval_proto_depIdxs = []int32{
	0, // 0: approval.v1.ApprovalService.SubscribeJobUpdates:input_type -> approval.v1.SubscribeRequest
	1, // 1: approval.v1.ApprovalService.NotifyJobUpdate:input_type -> approval.v1.JobUpdateNotification
	1, // 2: approval.v1.ApprovalService.SubscribeJobUpdates:output_type -> approval.v1.JobUpdateNotification
	2, // 3: approval.v1.ApprovalService.NotifyJobUpdate:output_type -> approval.v1.NotifyJobUpdateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_approval_proto_init() }
func file_api_proto_approval_proto_init() {
	if File_api_proto_approval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_approval_proto_rawDesc), len(file_api_proto_approval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_approval_proto_goTypes,
		DependencyIndexes: file_api_proto_approval_proto_depIdxs,
		MessageInfos:      file_api_proto_approval_proto_msgTypes,
	}.Build()
	File_api_proto_approval_proto = out.File
	file_api_proto_approval_proto_goTypes = nil
	file_api_proto_approval_proto_depIdxs = nil
}
