// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/orchestrator.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Platforms     []string               `protobuf:"bytes,4,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Caption       string                 `protobuf:"bytes,5,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitJobRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SubmitJobRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SubmitJobRequest) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *SubmitJobRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	WsUrl         string                 `protobuf:"bytes,3,opt,name=ws_url,json=wsUrl,proto3" json:"ws_url,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,4,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitJobResponse) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

func (x *SubmitJobResponse) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PostResultMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Platform       string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PlatformPostId string                 `protobuf:"bytes,6,opt,name=platform_post_id,json=platformPostId,proto3" json:"platform_post_id,omitempty"`
	PlatformUrl    string                 `protobuf:"bytes,7,opt,name=platform_url,json=platformUrl,proto3" json:"platform_url,omitempty"`
	ErrorDetail    string                 `protobuf:"bytes,8,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	AttemptCount   int32                  `protobuf:"varint,9,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	CreatedAtUnix  int64                  `protobuf:"varint,10,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostResultMsg) Reset() {
	*x = PostResultMsg{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResultMsg) ProtoMessage() {}

func (x *PostResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResultMsg.ProtoReflect.Descriptor instead.
func (*PostResultMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *PostResultMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostResultMsg) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PostResultMsg) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostResultMsg) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PostResultMsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PostResultMsg) GetPlatformPostId() string {
	if x != nil {
		return x.PlatformPostId
	}
	return ""
}

func (x *PostResultMsg) GetPlatformUrl() string {
	if x != nil {
		return x.PlatformUrl
	}
	return ""
}

func (x *PostResultMsg) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *PostResultMsg) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *PostResultMsg) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type GetJobResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OriginalPrompt    string                 `protobuf:"bytes,3,opt,name=original_prompt,json=originalPrompt,proto3" json:"original_prompt,omitempty"`
	RefinedPrompt     string                 `protobuf:"bytes,4,opt,name=refined_prompt,json=refinedPrompt,proto3" json:"refined_prompt,omitempty"`
	OriginalImageUrl  string                 `protobuf:"bytes,5,opt,name=original_image_url,json=originalImageUrl,proto3" json:"original_image_url,omitempty"`
	GeneratedImageUrl string                 `protobuf:"bytes,6,opt,name=generated_image_url,json=generatedImageUrl,proto3" json:"generated_image_url,omitempty"`
	PostResults       []*PostResultMsg       `protobuf:"bytes,7,rep,name=post_results,json=postResults,proto3" json:"post_results,omitempty"`
	CreatedAtUnix     int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobResponse) GetOriginalPrompt() string {
	if x != nil {
		return x.OriginalPrompt
	}
	return ""
}

func (x *GetJobResponse) GetRefinedPrompt() string {
	if x != nil {
		return x.RefinedPrompt
	}
	return ""
}

func (x *GetJobResponse) GetOriginalImageUrl() string {
	if x != nil {
		return x.OriginalImageUrl
	}
	return ""
}

func (x *GetJobResponse) GetGeneratedImageUrl() string {
	if x != nil {
		return x.GeneratedImageUrl
	}
	return ""
}

func (x *GetJobResponse) GetPostResults() []*PostResultMsg {
	if x != nil {
		return x.PostResults
	}
	return nil
}

func (x *GetJobResponse) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type ApproveJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	Platforms     []string               `protobuf:"bytes,4,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveJobRequest) Reset() {
	*x = ApproveJobRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveJobRequest) ProtoMessage() {}

func (x *ApproveJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveJobRequest.ProtoReflect.Descriptor instead.
func (*ApproveJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ApproveJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApproveJobRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *ApproveJobRequest) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type RejectJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectJobRequest) Reset() {
	*x = RejectJobRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectJobRequest) ProtoMessage() {}

func (x *RejectJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectJobRequest.ProtoReflect.Descriptor instead.
func (*RejectJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *RejectJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RejectJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RejectJobRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type JobActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobActionResponse) Reset() {
	*x = JobActionResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobActionResponse) ProtoMessage() {}

func (x *JobActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobActionResponse.ProtoReflect.Descriptor instead.
func (*JobActionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *JobActionResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobActionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_orchestrator_proto protoreflect.FileDescriptor

const file_api_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/orchestrator.proto\x12\x0forchestrator.v1\"\x98\x01\n" +
	"\x10SubmitJobRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1c\n" +
	"\tplatforms\x18\x04 \x03(\tR\tplatforms\x12\x18\n" +
	"\acaption\x18\x05 \x01(\tR\acaption\"\x81\x01\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x15\n" +
	"\x06ws_url\x18\x03 \x01(\tR\x05wsUrl\x12&\n" +
	"\x0fcreated_at_unix\x18\x04 \x01(\x03R\rcreatedAtUnix\"?\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xc0\x02\n" +
	"\rPostResultMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12(\n" +
	"\x10platform_post_id\x18\x06 \x01(\tR\x0eplatformPostId\x12!\n" +
	"\fplatform_url\x18\a \x01(\tR\vplatformUrl\x12!\n" +
	"\ferror_detail\x18\b \x01(\tR\verrorDetail\x12#\n" +
	"\rattempt_count\x18\t \x01(\x05R\fattemptCount\x12&\n" +
	"\x0fcreated_at_unix\x18\n" +
	" \x01(\x03R\rcreatedAtUnix\"\xd1\x02\n" +
	"\x0eGetJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0foriginal_prompt\x18\x03 \x01(\tR\x0eoriginalPrompt\x12%\n" +
	"\x0erefined_prompt\x18\x04 \x01(\tR\rrefinedPrompt\x12,\n" +
	"\x12original_image_url\x18\x05 \x01(\tR\x10originalImageUrl\x12.\n" +
	"\x13generated_image_url\x18\x06 \x01(\tR\x11generatedImageUrl\x12A\n" +
	"\fpost_results\x18\a \x03(\v2\x1e.orchestrator.v1.PostResultMsgR\vpostResults\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\"{\n" +
	"\x11ApproveJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\x12\x1c\n" +
	"\tplatforms\x18\x04 \x03(\tR\tplatforms\"Z\n" +
	"\x10RejectJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\\\n" +
	"\x11JobActionResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xde\x02\n" +
	"\x13OrchestratorService\x12R\n" +
	"\tSubmitJob\x12!.orchestrator.v1.SubmitJobRequest\x1a\".orchestrator.v1.SubmitJobResponse\x12I\n" +
	"\x06GetJob\x12\x1e.orchestrator.v1.GetJobRequest\x1a\x1f.orchestrator.v1.GetJobResponse\x12T\n" +
	"\n" +
	"ApproveJob\x12\".orchestrator.v1.ApproveJobRequest\x1a\".orchestrator.v1.JobActionResponse\x12R\n" +
	"\tRejectJob\x12!.orchestrator.v1.RejectJobRequest\x1a\".orchestrator.v1.JobActionResponseB\x1cZ\x1amyAgent/api/orchestratorpbb\x06proto3"

var (
	file_api_proto_orchestrator_proto_rawDescOnce sync.Once
	file_api_proto_orchestrator_proto_rawDescData []byte
)

func file_api_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_api_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_api_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_proto_rawDesc), len(file_api_proto_orchestrator_proto_rawDesc)))
	})
	return file_api_proto_orchestrator_proto_rawDescData
}

var file_api_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_orchestrator_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),  // 0: orchestrator.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil), // 1: orchestrator.v1.SubmitJobResponse
	(*GetJobRequest)(nil),     // 2: orchestrator.v1.GetJobRequest
	(*PostResultMsg)(nil),     // 3: orchestrator.v1.PostResultMsg
	(*GetJobResponse)(nil),    // 4: orchestrator.v1.GetJobResponse
	(*ApproveJobRequest)(nil), // 5: orchestrator.v1.ApproveJobRequest
	(*RejectJobRequest)(nil),  // 6: orchestrator.v1.RejectJobRequest
	(*JobActionResponse)(nil), // 7: orchestrator.v1.JobActionResponse
}
var file_api_proto_orchestrator_proto_depIdxs = []int32{
	3, // 0: orchestrator.v1.GetJobResponse.post_results:type_name -> orchestrator.v1.PostResultMsg
	0, // 1: orchestrator.v1.OrchestratorService.SubmitJob:input_type -> orchestrator.v1.SubmitJobRequest
	2, // 2: orchestrator.v1.OrchestratorService.GetJob:input_type -> orchestrator.v1.GetJobRequest
	5, // 3: orchestrator.v1.OrchestratorService.ApproveJob:input_type -> orchestrator.v1.ApproveJobRequest
	6, // 4: orchestrator.v1.OrchestratorService.RejectJob:input_type -> orchestrator.v1.RejectJobRequest
	1, // 5: orchestrator.v1.OrchestratorService.SubmitJob:output_type -> orchestrator.v1.SubmitJobResponse
	4, // 6: orchestrator.v1.OrchestratorService.GetJob:output_type -> orchestrator.v1.GetJobResponse
	7, // 7: orchestrator.v1.OrchestratorService.ApproveJob:output_type -> orchestrator.v1.JobActionResponse
	7, // 8: orchestrator.v1.OrchestratorService.RejectJob:output_type -> orchestrator.v1.JobActionResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_orchestrator_proto_init() }
func file_api_proto_orchestrator_proto_init() {
	if File_api_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_proto_rawDesc), len(file_api_proto_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_api_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_api_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_api_proto_orchestrator_proto = out.File
	file_api_proto_orchestrator_proto_goTypes = nil
	file_api_proto_orchestrator_proto_depIdxs = nil
}
