package types

import "time"

// PromptRefinementJob is published to prompt.refine.requested by the
// orchestrator and consumed by the prompt-agent.
type PromptRefinementJob struct {
	JobID          string            `json:"job_id"`
	UserID         string            `json:"user_id"`
	OriginalPrompt string            `json:"original_prompt"`
	ImageURL       string            `json:"image_url"`
	ExecutionPlan  ExecutionPlan     `json:"execution_plan"`
	TraceCtx       map[string]string `json:"trace_ctx"`
	PublishedAt    time.Time         `json:"published_at"`
}

// RefinedPromptEvent is published to prompt.refined by the prompt-agent
// and consumed by the image-gen-agent.
type RefinedPromptEvent struct {
	JobID            string            `json:"job_id"`
	UserID           string            `json:"user_id"`
	RefinedPrompt    string            `json:"refined_prompt"`
	StyleParams      StyleParams       `json:"style_params"`
	OriginalImageURL string            `json:"original_image_url"`
	TraceCtx         map[string]string `json:"trace_ctx"`
}

// ImageGeneratedEvent is published to image.generated by the image-gen-agent
// and consumed by the approval-service.
type ImageGeneratedEvent struct {
	JobID         string            `json:"job_id"`
	UserID        string            `json:"user_id"`
	ImageURL      string            `json:"image_url"`
	ComfyPromptID string            `json:"comfy_prompt_id"`
	GenerationMs  int64             `json:"generation_ms"`
	TraceCtx      map[string]string `json:"trace_ctx"`
}

// ImageApprovedEvent is published to image.approved by the approval-service
// and consumed by the distribution-service.
type ImageApprovedEvent struct {
	JobID     string            `json:"job_id"`
	UserID    string            `json:"user_id"`
	ImageURL  string            `json:"image_url"`
	Caption   string            `json:"caption"`
	Platforms []string          `json:"platforms"`
	TraceCtx  map[string]string `json:"trace_ctx"`
}

// JobFailedEvent is published to job.failed by any agent when an
// unrecoverable error occurs. Consumed by the orchestrator.
type JobFailedEvent struct {
	JobID        string            `json:"job_id"`
	UserID       string            `json:"user_id"`
	FailedAt     string            `json:"failed_at"`
	ErrorMessage string            `json:"error_message"`
	TraceCtx     map[string]string `json:"trace_ctx"`
}
